# Generated by Django 4.2.1 on 2023-06-21 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('Sol Oasis', 'Sol Oasis'), ('Movenpick', 'Movenpick'), ('Riad la Parenthese', 'Riad la Parenthese')], max_length=255)),
                ('number_of_persons', models.PositiveIntegerField()),
                ('reservation_date', models.DateField()),
            ],
        ),
    ]
